version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: rooflet-mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: rooflet_db
    ports:
      - "7003:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - rooflet-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root" ]
      timeout: 20s
      retries: 10
      interval: 30s
      start_period: 30s

  app:
    build: .
    restart: always
    container_name: rooflet-app
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/rooflet_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
    ports:
      - "7001:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - rooflet-network

volumes:
  mysql_data:

networks:
  rooflet-network:
    driver: bridge
